# Generated by Django 3.2.3 on 2021-05-18 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='category_id',
            field=models.IntegerField(),
        ),
    ]
