# Generated by Django 3.2.3 on 2021-06-16 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210614_1330'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
